build docker image with podman

diff --git a/.github/workflows/_docker-build.yml b/.github/workflows/_docker-build.yml
--- a/.github/workflows/_docker-build.yml
+++ b/.github/workflows/_docker-build.yml
@@ -1,6 +1,8 @@
 name: Reusable build and push
 
 on:
+  push:
+    branches: [ add-kaniko ]
   workflow_call:
     inputs:
       dockerfile:
@@ -10,17 +12,18 @@ on:
       feature-branch-image-tag:
         description: "Tag to apply to the Docker image when workflow runs on a feature branch"
         type: string
-        default: ""
+        default: "podman"
       default-branch-image-tag:
         description: "Tag to apply to the Docker image when workflow runs on the default branch"
         type: string
-        default: "latest"
+        default: "podman"
 
 permissions:
   id-token: write
 
 jobs:
   set-runner-uuid:
+    if: github.event_name == 'push'
     name: Set runner UUID
     runs-on: ubuntu-latest
     outputs:
@@ -31,6 +34,7 @@ jobs:
         run: echo "runner-uuid=$(uuidgen)" >> $GITHUB_OUTPUT
 
   build-and-test:
+    if: github.event_name == 'push'
     name: Build and test the runner image
     runs-on: ubuntu-latest
     needs: set-runner-uuid
@@ -107,88 +111,88 @@ jobs:
       - name: Push Docker image to ECR with just SHA tag
         run: docker push ${{ steps.set-image-tag-with-repo.outputs.image-tag-with-repo }}
 
-  run-docker-image:
-    name: Run Docker image
-    needs: [ set-runner-uuid, build-and-test ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: us-east-1
-          role-to-assume: ${{ secrets.OIDC_IAM_ROLE_ARN }}
+  # run-docker-image:
+  #   name: Run Docker image
+  #   needs: [ set-runner-uuid, build-and-test ]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-region: us-east-1
+  #         role-to-assume: ${{ secrets.OIDC_IAM_ROLE_ARN }}
 
-      - name: Log in to ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
+  #     - name: Log in to ECR
+  #       id: login-ecr
+  #       uses: aws-actions/amazon-ecr-login@v2
 
-      - name: Run Docker image
-        run: |
-          docker run --rm \
-          -e REPO_OWNER=${{ github.repository_owner }} \
-          -e REPO_NAME=$(basename ${{ github.repository }}) \
-          -e PERSONAL_ACCESS_TOKEN=${{ secrets.SERVICE_ACCOUNT_GITHUB_TOKEN }} \
-          -e RUNNER_UUID=${{ needs.set-runner-uuid.outputs.runner-uuid }} \
-          ${{ needs.build-and-test.outputs.image-tag-with-repo }}
+  #     - name: Run Docker image
+  #       run: |
+  #         docker run --rm \
+  #         -e REPO_OWNER=${{ github.repository_owner }} \
+  #         -e REPO_NAME=$(basename ${{ github.repository }}) \
+  #         -e PERSONAL_ACCESS_TOKEN=${{ secrets.SERVICE_ACCOUNT_GITHUB_TOKEN }} \
+  #         -e RUNNER_UUID=${{ needs.set-runner-uuid.outputs.runner-uuid }} \
+  #         ${{ needs.build-and-test.outputs.image-tag-with-repo }}
 
-  wait-for-runner:
-    name: Wait for the runner to be ready
-    needs: [ set-runner-uuid, build-and-test ]
-    runs-on: ubuntu-latest
-    timeout-minutes: 10
-    steps:
-      - name: Poll the GitHub Actions API until the runner is registered and online
-        run: |
-          response_file=$(mktemp)
-          until \
-            status=$(curl -s \
-              -H "Accept: application/vnd.github.v3+json" \
-              -u robot-mac-fc:${{ secrets.SERVICE_ACCOUNT_GITHUB_TOKEN }} \
-              -o $response_file \
-              -w "%{http_code}" \
-              --url https://api.github.com/repos/${{ github.repository }}/actions/runners
-            )
+  # wait-for-runner:
+  #   name: Wait for the runner to be ready
+  #   needs: [ set-runner-uuid, build-and-test ]
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 10
+  #   steps:
+  #     - name: Poll the GitHub Actions API until the runner is registered and online
+  #       run: |
+  #         response_file=$(mktemp)
+  #         until \
+  #           status=$(curl -s \
+  #             -H "Accept: application/vnd.github.v3+json" \
+  #             -u robot-mac-fc:${{ secrets.SERVICE_ACCOUNT_GITHUB_TOKEN }} \
+  #             -o $response_file \
+  #             -w "%{http_code}" \
+  #             --url https://api.github.com/repos/${{ github.repository }}/actions/runners
+  #           )
 
-            if [ $? -ne 0 ] || [ $status -ne 200 ]; then
-              echo "error getting runner status from GitHub"
-              echo "curl exited with code $?"
-              echo "response status: $status"
-              echo "response body: $(cat $response_file)"
-              exit 1
-            fi
+  #           if [ $? -ne 0 ] || [ $status -ne 200 ]; then
+  #             echo "error getting runner status from GitHub"
+  #             echo "curl exited with code $?"
+  #             echo "response status: $status"
+  #             echo "response body: $(cat $response_file)"
+  #             exit 1
+  #           fi
 
-            cat $response_file | jq -e '.runners | .[] | select(.name == "${{ needs.set-runner-uuid.outputs.runner-uuid }}") | .status == "online"' >/dev/null
-          do
-            echo "Waiting for runner ${{ needs.set-runner-uuid.outputs.runner-uuid }} to be ready" && sleep 10
-          done
-          echo "Runner ${{ needs.set-runner-uuid.outputs.runner-uuid }} is ready"
+  #           cat $response_file | jq -e '.runners | .[] | select(.name == "${{ needs.set-runner-uuid.outputs.runner-uuid }}") | .status == "online"' >/dev/null
+  #         do
+  #           echo "Waiting for runner ${{ needs.set-runner-uuid.outputs.runner-uuid }} to be ready" && sleep 10
+  #         done
+  #         echo "Runner ${{ needs.set-runner-uuid.outputs.runner-uuid }} is ready"
 
-  test-runner:
-    name: Test the runner
-    needs: [ set-runner-uuid, wait-for-runner ]
-    runs-on:
-      - self-hosted
-      - ${{ needs.set-runner-uuid.outputs.runner-uuid }}
-    timeout-minutes: 5
-    steps:
-      - name: Test the runner
-        run: echo "Self-hosted runner test was successful!"
+  # test-runner:
+  #   name: Test the runner
+  #   needs: [ set-runner-uuid, wait-for-runner ]
+  #   runs-on:
+  #     - self-hosted
+  #     - ${{ needs.set-runner-uuid.outputs.runner-uuid }}
+  #   timeout-minutes: 5
+  #   steps:
+  #     - name: Test the runner
+  #       run: echo "Self-hosted runner test was successful!"
 
-  add-tag-if-default-branch:
-    name: Add tag to image if running on the default branch
-    if: ${{ github.ref_name == github.event.repository.default_branch }}
-    needs: [test-runner, build-and-test]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: us-east-1
-          role-to-assume: ${{ secrets.OIDC_IAM_ROLE_ARN }}
+  # add-tag-if-default-branch:
+  #   name: Add tag to image if running on the default branch
+  #   if: ${{ github.ref_name == github.event.repository.default_branch }}
+  #   needs: [test-runner, build-and-test]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-region: us-east-1
+  #         role-to-assume: ${{ secrets.OIDC_IAM_ROLE_ARN }}
 
-      - name: Add default branch tag to image
-        uses: abronin/ecr-retag-action@v1
-        with:
-          repository: github-actions-runner
-          tag: ${{ needs.build-and-test.outputs.image-tag-with-sha }}
-          new-tags: ${{ inputs.default-branch-image-tag }}
+  #     - name: Add default branch tag to image
+  #       uses: abronin/ecr-retag-action@v1
+  #       with:
+  #         repository: github-actions-runner
+  #         tag: ${{ needs.build-and-test.outputs.image-tag-with-sha }}
+  #         new-tags: ${{ inputs.default-branch-image-tag }}
